### ISSUE TITLE
Parameter "options" needs to be a real object but type "string" has been passedBug report

### ISSUE THREAD

**Issue by raintonr** [ice987987/ioBroker.meteoblue#155]
### The problem

Fresh install and on startup see the error below:

```
2023-12-16 11:39:18.077  - info: meteoblue.0 (2247693) starting. Version 0.0.6 in /opt/iobroker/node_modules/iobroker.meteoblue, node: v18.16.0, js-controller: 5.0.17
2023-12-16 11:39:18.094  - info: meteoblue.0 (2247693) starting adapter "meteoblue"...
2023-12-16 11:39:18.097  - error: meteoblue.0 (2247693) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-12-16 11:39:18.098  - error: meteoblue.0 (2247693) unhandled promise rejection: Parameter "options" needs to be a real object but type "string" has been passed
2023-12-16 11:39:18.100  - error: meteoblue.0 (2247693) Error: Parameter "options" needs to be a real object but type "string" has been passed
    at Validator.assertObject (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/validator.js:215:19)
    at Meteoblue.getForeignObject (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:3056:35)
    at /opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2022:16
    at new Promise (<anonymous>)
    at Meteoblue.getForeignObjectAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2021:16)
    at Meteoblue.onReady (/opt/iobroker/node_modules/iobroker.meteoblue/main.js:66:28)
    at Meteoblue.emit (node:events:513:28)
    at Meteoblue._callReadyHandler (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9118:18)
    at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9097:26
2023-12-16 11:39:18.100  - error: meteoblue.0 (2247693) Parameter "options" needs to be a real object but type "string" has been passed
2023-12-16 11:39:18.108  - info: meteoblue.0 (2247693) terminating
2023-12-16 11:39:18.108  - warn: meteoblue.0 (2247693) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-12-16 11:39:18.108  - info: meteoblue.0 (2247693) cleaned everything up... (#1)
2023-12-16 11:39:18.611  - info: meteoblue.0 (2247693) terminating
```

### Version of Node.js

v18.16.0

### Version of ioBroker js-controller

5.0.17

### Version of "meteoblue"-adapter

0.0.6

### Version of "admin"-adapter

6.12.0

### Operating system incl. version running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode and check that there are no personal information)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by ice987987** [comment]
could you please try ioBroker.meteoblue v0.1.0-beta.10

**Comment by raintonr** [comment]
Yes, that's better, thx :+1:
